"""make_created_by_id_nullable

Revision ID: 5147f97961d4
Revises: 211399e393b9
Create Date: 2025-12-12 12:36:03.806357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5147f97961d4'
down_revision = '211399e393b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
