"""add_streak_count_to_profiles

Revision ID: 6d5c1f7b9520
Revises: 5147f97961d4
Create Date: 2025-12-12 16:44:47.511445

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "6d5c1f7b9520"
down_revision = "5147f97961d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("streak_count", sa.Integer(), nullable=False))
    op.add_column(
        "profiles",
        sa.Column(
            "last_active_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "last_active_date")
    op.drop_column("profiles", "streak_count")
    # ### end Alembic commands ###
