"""initial_schema

Revision ID: 211399e393b9
Revises:
Create Date: 2025-12-12 11:49:04.188933

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "211399e393b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_departments_name"), "departments", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "hashed_password",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("EMPLOYEE", "ADMIN", "SUPER_ADMIN", "MANAGER", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_department_id"), "users", ["department_id"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_manager_id"), "users", ["manager_id"], unique=False)
    op.create_table(
        "badges",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "badge_type",
            sa.Enum("BRONZE", "SILVER", "GOLD", "PLATINUM", name="badgetype"),
            nullable=False,
        ),
        sa.Column("year_earned", sa.Integer(), nullable=False),
        sa.Column("hours_completed", sa.Float(), nullable=False),
        sa.Column("trainings_completed", sa.Integer(), nullable=False),
        sa.Column(
            "awarded_at", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_badges_badge_type"), "badges", ["badge_type"], unique=False
    )
    op.create_index(op.f("ix_badges_user_id"), "badges", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_badges_year_earned"), "badges", ["year_earned"], unique=False
    )
    op.create_table(
        "certifications",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "issuing_organization",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "credential_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "credential_url",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_certifications_user_id"), "certifications", ["user_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "notification_type",
            sa.Enum(
                "TRAINING_ASSIGNED",
                "TRAINING_APPROVED",
                "TRAINING_REJECTED",
                "SESSION_SCHEDULED",
                "SESSION_REMINDER",
                "TRAINING_COMPLETED",
                "BADGE_EARNED",
                "DEADLINE_APPROACHING",
                name="notificationtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "message", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "action_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "location", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("tech_stack", sa.JSON(), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("total_learning_hours", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "trainings",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False
        ),
        sa.Column(
            "category", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_APPROVAL",
                "APPROVED",
                "REJECTED",
                "SCHEDULED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="trainingstatus",
            ),
            nullable=False,
        ),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column(
            "rejection_reason",
            sqlmodel.sql.sqltypes.AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("prerequisites", sa.JSON(), nullable=True),
        sa.Column("learning_objectives", sa.JSON(), nullable=True),
        sa.Column(
            "materials_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trainings_category"), "trainings", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_trainings_created_by_id"), "trainings", ["created_by_id"], unique=False
    )
    op.create_index(op.f("ix_trainings_status"), "trainings", ["status"], unique=False)
    op.create_index(op.f("ix_trainings_title"), "trainings", ["title"], unique=False)
    op.create_table(
        "training_sessions",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("training_id", sa.Uuid(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column(
            "start_time", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False
        ),
        sa.Column(
            "end_time", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False
        ),
        sa.Column(
            "location", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "instructor_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("current_participants", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_sessions_session_date"),
        "training_sessions",
        ["session_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_sessions_training_id"),
        "training_sessions",
        ["training_id"],
        unique=False,
    )
    op.create_table(
        "enrollments",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("training_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ENROLLED",
                "IN_PROGRESS",
                "COMPLETED",
                "DROPPED",
                "FAILED",
                name="enrollmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("is_assigned", sa.Boolean(), nullable=False),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("completion_percentage", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enrollments_session_id"), "enrollments", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollments_status"), "enrollments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_enrollments_training_id"), "enrollments", ["training_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollments_user_id"), "enrollments", ["user_id"], unique=False
    )
    op.create_table(
        "attendance",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("attendance_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PRESENT", "ABSENT", "PARTIAL", name="attendancestatus"),
            nullable=False,
        ),
        sa.Column("hours_attended", sa.Float(), nullable=False),
        sa.Column(
            "notes", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_attendance_date"),
        "attendance",
        ["attendance_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_enrollment_id"),
        "attendance",
        ["enrollment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_session_id"), "attendance", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_attendance_user_id"), "attendance", ["user_id"], unique=False
    )
    op.create_table(
        "training_completions",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("training_id", sa.Uuid(), nullable=False),
        sa.Column("enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("learning_hours", sa.Float(), nullable=False),
        sa.Column("attendance_percentage", sa.Float(), nullable=False),
        sa.Column("assessment_score", sa.Float(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("certificate_issued", sa.Boolean(), nullable=False),
        sa.Column(
            "certificate_url",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_id"],
            ["trainings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_completions_enrollment_id"),
        "training_completions",
        ["enrollment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_training_completions_training_id"),
        "training_completions",
        ["training_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_completions_user_id"),
        "training_completions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_training_completions_user_id"), table_name="training_completions"
    )
    op.drop_index(
        op.f("ix_training_completions_training_id"), table_name="training_completions"
    )
    op.drop_index(
        op.f("ix_training_completions_enrollment_id"), table_name="training_completions"
    )
    op.drop_table("training_completions")
    op.drop_index(op.f("ix_attendance_user_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_session_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_enrollment_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_attendance_date"), table_name="attendance")
    op.drop_table("attendance")
    op.drop_index(op.f("ix_enrollments_user_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_training_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_status"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_session_id"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(
        op.f("ix_training_sessions_training_id"), table_name="training_sessions"
    )
    op.drop_index(
        op.f("ix_training_sessions_session_date"), table_name="training_sessions"
    )
    op.drop_table("training_sessions")
    op.drop_index(op.f("ix_trainings_title"), table_name="trainings")
    op.drop_index(op.f("ix_trainings_status"), table_name="trainings")
    op.drop_index(op.f("ix_trainings_created_by_id"), table_name="trainings")
    op.drop_index(op.f("ix_trainings_category"), table_name="trainings")
    op.drop_table("trainings")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(
        op.f("ix_notifications_notification_type"), table_name="notifications"
    )
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_certifications_user_id"), table_name="certifications")
    op.drop_table("certifications")
    op.drop_index(op.f("ix_badges_year_earned"), table_name="badges")
    op.drop_index(op.f("ix_badges_user_id"), table_name="badges")
    op.drop_index(op.f("ix_badges_badge_type"), table_name="badges")
    op.drop_table("badges")
    op.drop_index(op.f("ix_users_manager_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_departments_name"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
